// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthAccount struct {
	ID                string
	UserID            string
	Provider          string
	ProviderAccountID string
	CreatedAt         pgtype.Timestamptz
}

type AuthUser struct {
	ID        string
	Name      *string
	Phone     *string
	Role      string
	CreatedAt pgtype.Timestamptz
}

type AuthVerificationToken struct {
	Identifier string
	Token      string
	Expires    pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}
