// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearOTPTokens = `-- name: ClearOTPTokens :exec
DELETE FROM auth.verification_tokens WHERE identifier = $1
`

func (q *Queries) ClearOTPTokens(ctx context.Context, identifier string) error {
	_, err := q.db.Exec(ctx, clearOTPTokens, identifier)
	return err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO auth.accounts (user_id, provider, provider_account_id)
      VALUES ($1, $2, $3)
`

type InsertAccountParams struct {
	UserID            string
	Provider          string
	ProviderAccountID string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount, arg.UserID, arg.Provider, arg.ProviderAccountID)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO auth.users (id, name, phone, role)
      VALUES ($1, $2, $3, 'USER')
   RETURNING id, role, name, phone
`

type InsertUserParams struct {
	ID    string
	Name  *string
	Phone *string
}

type InsertUserRow struct {
	ID    string
	Role  string
	Name  *string
	Phone *string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.ID, arg.Name, arg.Phone)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Name,
		&i.Phone,
	)
	return i, err
}

const lookupUserByPhone = `-- name: LookupUserByPhone :one

SELECT u.id, u.role, u.name, a.provider_account_id as phone
  FROM auth.users u
  JOIN auth.accounts a ON u.id = a.user_id
 WHERE a.provider = $1 AND a.provider_account_id = $2
 LIMIT 1
`

type LookupUserByPhoneParams struct {
	Provider          string
	ProviderAccountID string
}

type LookupUserByPhoneRow struct {
	ID    string
	Role  string
	Name  *string
	Phone string
}

// Identity queries
func (q *Queries) LookupUserByPhone(ctx context.Context, arg LookupUserByPhoneParams) (LookupUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, lookupUserByPhone, arg.Provider, arg.ProviderAccountID)
	var i LookupUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Name,
		&i.Phone,
	)
	return i, err
}

const storeOTPToken = `-- name: StoreOTPToken :exec

INSERT INTO auth.verification_tokens (identifier, token, expires)
      VALUES ($1, $2, $3)
 ON CONFLICT DO NOTHING
`

type StoreOTPTokenParams struct {
	Identifier string
	Token      string
	Expires    pgtype.Timestamptz
}

// OTP queries
func (q *Queries) StoreOTPToken(ctx context.Context, arg StoreOTPTokenParams) error {
	_, err := q.db.Exec(ctx, storeOTPToken, arg.Identifier, arg.Token, arg.Expires)
	return err
}

const verifyOTPToken = `-- name: VerifyOTPToken :execrows
DELETE FROM auth.verification_tokens
      WHERE identifier = $1 AND token = $2 AND expires > now()
`

type VerifyOTPTokenParams struct {
	Identifier string
	Token      string
}

// VerifyOTPToken consumes a code; the caller treats 0 affected rows as a
// wrong/expired code.
func (q *Queries) VerifyOTPToken(ctx context.Context, arg VerifyOTPTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, verifyOTPToken, arg.Identifier, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
