"""simplify cart_checkout

Revision ID: 6c455115cd4d
Revises: 9e5f4288a1f5
Create Date: 2026-06-25 10:58:46.761533

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "6c455115cd4d"
down_revision: str | None = "9e5f4288a1f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_customer_cart_checkouts_checkout_ref"), table_name="customer_cart_checkouts"
    )
    op.drop_column("customer_cart_checkouts", "summary")
    op.drop_column("customer_cart_checkouts", "status")
    op.drop_column("customer_cart_checkouts", "checkout_ref")
    op.drop_column("customer_cart_checkouts", "expires_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer_cart_checkouts",
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "customer_cart_checkouts",
        sa.Column("checkout_ref", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    )
    op.add_column(
        "customer_cart_checkouts",
        sa.Column(
            "status",
            sa.VARCHAR(length=32),
            server_default=sa.text("'awaiting_payment'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "customer_cart_checkouts",
        sa.Column(
            "summary",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_customer_cart_checkouts_checkout_ref"),
        "customer_cart_checkouts",
        ["checkout_ref"],
        unique=False,
    )
    # ### end Alembic commands ###
