"""remove last_order from customer_profile

Revision ID: 9e5f4288a1f5
Revises: 0008_sep_cart_tracking
Create Date: 2026-06-25 10:52:52.946411

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "9e5f4288a1f5"
down_revision: str | None = "0008_sep_cart_tracking"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer_profiles", "last_order")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer_profiles",
        sa.Column(
            "last_order",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
