# app/domain/ports.py
from typing import Protocol, List, Dict

class ChatHistoryPort(Protocol):
    def get(self, chat_id: str) -> List[str]: ...
    def append(self, chat_id: str, question: str, answer: str) -> None: ...
    def reset(self, chat_id: str) -> None: ...

class RetrieverPort(Protocol):
    def topk(self, query: str, k: int) -> List[str]: ...

class LLMPort(Protocol):
    def generate(self, prompt: str, model: str | None = None) -> str: ...
